# Generated by Django 4.0.6 on 2022-07-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networksocial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follower',
        ),
        migrations.AddField(
            model_name='follower',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='following', to='networksocial.follower'),
        ),
    ]
